### ISSUE TITLE
Inquiry about t5-base model

### ISSUE THREAD

**Issue by soonchangAI** [fangbufang/SaL#8]
In <code>models/sal.py</code>, <code>"/data/fcy/sal/t5-base"</code> is not provided. 
Can I use the t5-base from Google https://huggingface.co/google-t5/t5-base/tree/main ?

**Comment by fangbufang** [comment]
Yes, t5-base and t5-large can be downloaded from https://huggingface.co/google-t5/t5-base/tree/main
