### ISSUE TITLE
Error when evaluating SAL TextVQA 

### ISSUE THREAD

**Issue by soonchangAI** [fangbufang/SaL#9]
I faced following error when evaluating on SAL TextVQA
```
assert self.PAD_IDX != self.answer_vocab.UNK_INDEX
AssertionError
```
It ran without error when I change the vocab file from <code>fixed_answer_vocab_textvqa_5k.txt</code> to ST-VQA's <code> fixed_answer_vocab_stvqa_5k.txt</code>

I observe the main difference is the provided TextVQA vocab file lacks a few tokens:
```
<pad>
<s>
</s>
<unk>
```

**Comment by fangbufang** [comment]
These two dictionary files are used in the M4C project. Our project is modified based on M4C. During the actual running process, these two files are not used, so you can directly comment out this line of code.
